# Generated by Django 3.2 on 2021-04-25 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopMovie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, height_field=67, upload_to='', width_field=45)),
                ('title', models.CharField(blank=True, max_length=125)),
                ('release_date', models.DateField(blank=True)),
                ('rating', models.FloatField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
