# Generated by Django 3.2 on 2021-04-26 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings_app', '0004_alter_topmovie_release_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topmovie',
            name='rating',
            field=models.CharField(max_length=4),
        ),
    ]
